name: Go Test and Build

on:
  push:
    branches: [ "main" ]

jobs:
  test-and-build:
    name: Test and Build CryptoSentry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'  # Specify your Go version here
      - run: go version

      - name: Download modules
        run: go mod download

      - name: Test
        run: go test -v ./... -bench . -cover > TestResults-1.23.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-1.23
          path: TestResults-1.23.json